### ISSUE TITLE
Allow login only to Corp/Ally/Member

### ISSUE THREAD

**Issue by H4Z4RD-H42** [fuzzysteve/WordpressSocialLogin-EveSSO#1]
Your plugin is the only one for now that allow login easily in wordpress with eve online data, i appreciate a lot your work because my corp need our website for some activities, but we need to restrict access to to resources. I use [oAuth by miniorange](https://it.wordpress.org/plugins/miniorange-login-with-eve-online-google-facebook/) for a while, but now they ask for 249€ license plan to use new SSO features lol ! This plugin have the feature to allow/negate login for corp/ally/member, check the screenshot.

If you can add this features, we appreciate very much. Thank you again.

![image](https://user-images.githubusercontent.com/6650832/39968100-f9438ca6-56c7-11e8-86ab-1e34d537f41b.png)

P.S. add your Eve Online nick, we can donate ISK.

**Comment by fuzzysteve** [comment]
Updated. By ID only, as I'm not going to get it to look them up at the moment.

You _could_ extend it if you wanted, in the settings plugin.

**Comment by H4Z4RD-H42** [comment]
After some issues (all eve players can login in my website, dunno why. Today i try for the third time to change some settings and now work fine. Members of my corp can login, the others receive a error message).

Just a question about the IDs. I found the ID of my corp from Dotlan/zKillboard. It's the same ID? I assume yes because your plugin work... but i tried to check your link ( https://esi.evetech.net/ui/#/Search/get_searc ) and i do not understand how to use it to check if ID is the same.

EDIT 2018/05/17: finally i understand how to use esi website and yes, the ID is the same of dotlan and zkill.
